### ISSUE TITLE
entityHasComponent method should return falseinstead of throwing an Error object when unknown component is found.

### ISSUE THREAD

**Issue by nykevinwong** [adngdb/entity-system-js#22]
see below example:

```javascript
EntityManager.prototype.entityHasComponent = function (entityId, componentId) {
        if (!(componentId in this.components)) {
  // comment out below line.  Users  shall decide when to throw ERROR if the component is not found.     
//   throw new Error('Trying to use unknown component: ' + componentId);

           return false; // return false when not found.
        }

        return (
            this.entityComponentData.hasOwnProperty(componentId) &&
            this.entityComponentData[componentId].hasOwnProperty(entityId)
        );
    };
'''

**Comment by adngdb** [comment]
I think I disagree with this. If you are trying to use a component that doesn't exist in the EntityManager's components list, that very probably means you have made a programming mistake. Either you misspelled the component's name, or you forgot to add that component to the manager. I believe that raising an error in such a case is the right thing to do, because it will catch the programmer's attention about their mistake. 

Happy to argue about this though.
