### ISSUE TITLE
Make a minified version available

### ISSUE THREAD

**Issue by adngdb** [adngdb/entity-system-js#7]

**Comment by AdrianGaudebert** [comment]
@maxailloud Do you have some experience with build systems for JavaScript, like grunt or gulp? Any recommendations?

**Comment by maxailloud** [comment]
Brunch I might say instead of them.

Cordialement,

AILLOUD Maxime
Le 8 juin 2015 18:38, "Adrian Gaudebert" <notifications@github.com> a
écrit :

**Comment by maxailloud** [comment]
I'll look at it when I have time, few days I guess.

2015-06-08 18:39 GMT+02:00 Maxime AILLOUD <maxime.ailloud@gmail.com>:

> Brunch I might say instead of them.
>
> Cordialement,
>
> AILLOUD Maxime
> Le 8 juin 2015 18:38, "Adrian Gaudebert" <notifications@github.com> a
> écrit :
>
>> @maxailloud <https://github.com/maxailloud> Do you have some experience
>> with build systems for JavaScript, like grunt or gulp? Any recommendations?
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/AdrianGaudebert/entity-system-js/issues/7#issuecomment-110068535>
>> .
>>
>


-- 
*Cordialement*,

Maxime AILLOUD

**Comment by AdrianGaudebert** [comment]
I tried ``brunch`` on a different project and didn't like it. I've been using ``webpack`` for building websites, but that might not be appropriate for a library. Maybe ``gulp`` is actually the right tool for this. Or maybe ``brunch`` will be appropriate since all that is needed here is to minify one single file. 

Also, it would be nice to have this library be usable from anywhere. I'll try importing it into various environments. Here's what I think users should be able to do: 

```html
<script src="ensy.js"></script>
<script>var manager = new EntityManager();</script>
```
```javascript
var EntityManager = require('ensy')
```
```javascript
import { EntityManager } from 'ensy'
```
```javascript
define(['ensy'], function (EntityManager) { ; })
```

**Comment by maxailloud** [comment]
Or maybe just uing a minifying tool, uglyfyJS or something like that I'm not really aware of all existing tools.
A build tool is maybe too much as we just want to minify one file?

**Comment by maxailloud** [comment]
Maybe just by using this method:
http://dotmobo.github.io/makefile-frontend.html

Could be a good one too.

**Comment by adngdb** [comment]
I have decided to go with rollup + babel + uglify.
